# Use postgres/example user/password credentials
version: '3.19'

services:
  db:
    volumes:
       - postgres_db:/var/lib/postgresql/data
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: hw12_api

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
    postgres_db:
      external: true